# Generated by Django 4.2.3 on 2023-09-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factwise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(max_length=260, null=True),
        ),
    ]
