# Generated by Django 4.2.3 on 2023-09-17 05:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('factwise', '0003_remove_user_team_id_userxteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factwise.team'),
        ),
    ]
