# Generated by Django 4.2.3 on 2023-09-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factwise', '0004_board_creation_time_board_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_status',
            field=models.CharField(default='OPEN', max_length=15),
        ),
    ]
