# Generated by Django 4.2.3 on 2023-09-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factwise', '0005_alter_board_board_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(default='OPEN', max_length=15),
        ),
    ]
