# Generated by Django 4.2.3 on 2023-09-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factwise', '0007_remove_team_board_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='end_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
